### ISSUE TITLE
Handle problems with the gazbin file.

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-StringAnnotation#20]
The fix for #6 throws an exception if there is a problem reading a gazbin file, if it exists. Now that we check for the serialisation id, loading anything from a previous version will cause a problem. 

This could be too annoying so we have the following options, possibly do both:
* do not throw an exception, but just show an error message and load from the list file instead. DO NOT replace the cache file: we ALWAYS expect this to get done by the user explicitly to avoid surprises.
* allow an init parameter to disable using a cache file at all

In addition, we should check if a gazbin file can be created and just warn if not. This is especially important for prepared pipelines where everything is in the jar. 

So for now:
* if there is a gazbin file but it cannot be loaded for whatever reason:
  * show a warning, suggest deleting
  * load from lst
* if there is no gazbin file, check if the gazbin file can be written:
  * if not a file url, do not write -- this is already handled by our UrlUtils.isFile() method
  * if we know we cannot write, show a warning and proceed
  * if a file url and we get an exception when writing: show a warning but proceed

**Comment by greenwoodma** [comment]
Sounds like a perfect way of handling the problems.

**Comment by johann-petrak** [comment]
OK, decided not to implement the parameter to not do caching for now, should be a separate issue if somebody really needs it.
