### ISSUE TITLE
gazbin files are version specific

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gateplugin-StringAnnotation#6]
I've no idea if it's really an issue or if we can do anything about it but.... it turns out that the gazbin files seem to store serialized classes without serial UUIDs which means that if the class changes (possibly just a recompile on a different java version) the gazbin files can't be loaded due to a ClassCastException.
Not sure what the ideal solution is here; maybe catch the exception and rebuild the cache if loading of it fails?

**Comment by johann-petrak** [comment]
I think the proper way would be to start using UUIDs properly and catch any present and future exceptions from mismatches and show an understandable message instead, telling the user to remove the gazbin. 
So far the idea is that it is always the user's responsibility to delete the file.

**Comment by johann-petrak** [comment]
Actually, there was already an issue in the issue tracker of the old version:
https://github.com/johann-petrak/gateplugin-StringAnnotation/issues/18

All the issues are getting copied/moved soon!

**Comment by greenwoodma** [comment]
Ah, I didn't realise that you hadn't simply transferred the old repo into the GateNLP account along with all it's issues and history.
